[template]
src = "consul.crt.tmpl"
dest = "/opt/rancher/ssl/consul.crt"
owner = "root"
mode = "0644"
keys = [
  "/self/service/metadata/consul1.crt",
  "/self/service/metadata/consul2.crt",
  "/self/service/metadata/consul3.crt",
  "/self/container/service_index",
  ]
